library verilog;
use verilog.vl_types.all;
entity fft256_asj_fft_pround_fft_121_1 is
    port(
        pipeline_dffe_16: out    vl_logic;
        pipeline_dffe_17: out    vl_logic;
        pipeline_dffe_18: out    vl_logic;
        pipeline_dffe_19: out    vl_logic;
        pipeline_dffe_20: out    vl_logic;
        pipeline_dffe_21: out    vl_logic;
        pipeline_dffe_22: out    vl_logic;
        pipeline_dffe_23: out    vl_logic;
        pipeline_dffe_24: out    vl_logic;
        pipeline_dffe_25: out    vl_logic;
        pipeline_dffe_26: out    vl_logic;
        pipeline_dffe_27: out    vl_logic;
        pipeline_dffe_28: out    vl_logic;
        pipeline_dffe_29: out    vl_logic;
        pipeline_dffe_30: out    vl_logic;
        pipeline_dffe_31: out    vl_logic;
        result_imag_1_16: in     vl_logic;
        result_imag_1_15: in     vl_logic;
        result_imag_1_14: in     vl_logic;
        result_imag_1_13: in     vl_logic;
        result_imag_1_12: in     vl_logic;
        result_imag_1_11: in     vl_logic;
        result_imag_1_10: in     vl_logic;
        result_imag_1_9 : in     vl_logic;
        result_imag_1_8 : in     vl_logic;
        result_imag_1_7 : in     vl_logic;
        result_imag_1_6 : in     vl_logic;
        result_imag_1_5 : in     vl_logic;
        result_imag_1_4 : in     vl_logic;
        result_imag_1_3 : in     vl_logic;
        result_imag_1_2 : in     vl_logic;
        result_imag_1_1 : in     vl_logic;
        result_imag_1_0 : in     vl_logic;
        result_imag_1_31: in     vl_logic;
        result_imag_1_17: in     vl_logic;
        result_imag_1_18: in     vl_logic;
        result_imag_1_19: in     vl_logic;
        result_imag_1_20: in     vl_logic;
        result_imag_1_21: in     vl_logic;
        result_imag_1_22: in     vl_logic;
        result_imag_1_23: in     vl_logic;
        result_imag_1_24: in     vl_logic;
        result_imag_1_25: in     vl_logic;
        result_imag_1_26: in     vl_logic;
        result_imag_1_27: in     vl_logic;
        result_imag_1_28: in     vl_logic;
        result_imag_1_29: in     vl_logic;
        result_imag_1_30: in     vl_logic;
        global_clock_enable: in     vl_logic;
        clk             : in     vl_logic
    );
end fft256_asj_fft_pround_fft_121_1;
