library verilog;
use verilog.vl_types.all;
entity fft256_auk_dspip_avalon_streaming_sink_fft_121 is
    port(
        master_sink_ena : in     vl_logic;
        q_b_16          : out    vl_logic;
        q_b_0           : out    vl_logic;
        q_b_17          : out    vl_logic;
        q_b_1           : out    vl_logic;
        q_b_18          : out    vl_logic;
        q_b_2           : out    vl_logic;
        q_b_19          : out    vl_logic;
        q_b_3           : out    vl_logic;
        q_b_20          : out    vl_logic;
        q_b_4           : out    vl_logic;
        q_b_21          : out    vl_logic;
        q_b_5           : out    vl_logic;
        q_b_22          : out    vl_logic;
        q_b_6           : out    vl_logic;
        q_b_23          : out    vl_logic;
        q_b_7           : out    vl_logic;
        q_b_24          : out    vl_logic;
        q_b_8           : out    vl_logic;
        q_b_25          : out    vl_logic;
        q_b_9           : out    vl_logic;
        q_b_26          : out    vl_logic;
        q_b_10          : out    vl_logic;
        q_b_27          : out    vl_logic;
        q_b_11          : out    vl_logic;
        q_b_28          : out    vl_logic;
        q_b_12          : out    vl_logic;
        q_b_29          : out    vl_logic;
        q_b_13          : out    vl_logic;
        q_b_30          : out    vl_logic;
        q_b_14          : out    vl_logic;
        q_b_31          : out    vl_logic;
        q_b_15          : out    vl_logic;
        at_sink_ready_s1: out    vl_logic;
        source_stall_reg: in     vl_logic;
        sink_stall_reg  : in     vl_logic;
        sink_ready_ctrl : in     vl_logic;
        sink_start1     : out    vl_logic;
        empty_dff       : out    vl_logic;
        sink_stall1     : out    vl_logic;
        packet_error_s_0: out    vl_logic;
        packet_error_s_1: out    vl_logic;
        send_sop_s1     : out    vl_logic;
        send_eop_s1     : out    vl_logic;
        clk             : in     vl_logic;
        reset_n         : in     vl_logic;
        sink_valid      : in     vl_logic;
        sink_sop        : in     vl_logic;
        sink_eop        : in     vl_logic;
        sink_error_0    : in     vl_logic;
        sink_error_1    : in     vl_logic;
        at_sink_data    : in     vl_logic_vector(31 downto 0)
    );
end fft256_auk_dspip_avalon_streaming_sink_fft_121;
