library verilog;
use verilog.vl_types.all;
entity fft256_asj_fft_dft_bfp_sgl_fft_121 is
    port(
        pipeline_dffe_16: out    vl_logic;
        pipeline_dffe_17: out    vl_logic;
        pipeline_dffe_18: out    vl_logic;
        pipeline_dffe_19: out    vl_logic;
        pipeline_dffe_20: out    vl_logic;
        pipeline_dffe_21: out    vl_logic;
        pipeline_dffe_22: out    vl_logic;
        pipeline_dffe_23: out    vl_logic;
        pipeline_dffe_24: out    vl_logic;
        pipeline_dffe_25: out    vl_logic;
        pipeline_dffe_26: out    vl_logic;
        pipeline_dffe_27: out    vl_logic;
        pipeline_dffe_28: out    vl_logic;
        pipeline_dffe_29: out    vl_logic;
        pipeline_dffe_30: out    vl_logic;
        pipeline_dffe_31: out    vl_logic;
        twiddle_data_real_0: in     vl_logic;
        twiddle_data_real_15: in     vl_logic;
        twiddle_data_imag_1: in     vl_logic;
        twiddle_data_imag_2: in     vl_logic;
        twiddle_data_imag_3: in     vl_logic;
        twiddle_data_imag_4: in     vl_logic;
        twiddle_data_imag_5: in     vl_logic;
        twiddle_data_imag_6: in     vl_logic;
        twiddle_data_imag_7: in     vl_logic;
        twiddle_data_imag_8: in     vl_logic;
        twiddle_data_imag_9: in     vl_logic;
        twiddle_data_imag_10: in     vl_logic;
        twiddle_data_imag_11: in     vl_logic;
        twiddle_data_imag_12: in     vl_logic;
        twiddle_data_imag_13: in     vl_logic;
        twiddle_data_imag_14: in     vl_logic;
        twiddle_data_imag_15: in     vl_logic;
        source_valid_ctrl_sop: in     vl_logic;
        stall_reg       : in     vl_logic;
        source_stall_int_d: in     vl_logic;
        global_clock_enable: in     vl_logic;
        slb_i_0         : out    vl_logic;
        Mux2            : out    vl_logic;
        lut_out_0       : out    vl_logic;
        tdl_arr_0       : in     vl_logic;
        Mux1            : out    vl_logic;
        lut_out_1       : out    vl_logic;
        lut_out_2       : out    vl_logic;
        lut_out_21      : out    vl_logic;
        real_out_0      : out    vl_logic;
        real_out_1      : out    vl_logic;
        real_out_2      : out    vl_logic;
        real_out_3      : out    vl_logic;
        real_out_4      : out    vl_logic;
        real_out_5      : out    vl_logic;
        real_out_6      : out    vl_logic;
        real_out_7      : out    vl_logic;
        real_out_8      : out    vl_logic;
        real_out_9      : out    vl_logic;
        real_out_10     : out    vl_logic;
        real_out_11     : out    vl_logic;
        real_out_12     : out    vl_logic;
        real_out_13     : out    vl_logic;
        real_out_14     : out    vl_logic;
        real_out_15     : out    vl_logic;
        tdl_arr_01      : in     vl_logic;
        k_count_0       : in     vl_logic;
        k_count_1       : in     vl_logic;
        twiddle_data_real_1: in     vl_logic;
        twiddle_data_real_2: in     vl_logic;
        twiddle_data_real_3: in     vl_logic;
        twiddle_data_real_4: in     vl_logic;
        twiddle_data_real_5: in     vl_logic;
        twiddle_data_real_6: in     vl_logic;
        twiddle_data_real_7: in     vl_logic;
        twiddle_data_real_8: in     vl_logic;
        twiddle_data_real_9: in     vl_logic;
        twiddle_data_real_10: in     vl_logic;
        twiddle_data_real_11: in     vl_logic;
        twiddle_data_real_12: in     vl_logic;
        twiddle_data_real_13: in     vl_logic;
        twiddle_data_real_14: in     vl_logic;
        twiddle_data_imag_0: in     vl_logic;
        ram_data_out_0  : in     vl_logic;
        ram_data_out_2  : in     vl_logic;
        slb_last_1      : in     vl_logic;
        ram_data_out_1  : in     vl_logic;
        slb_last_0      : in     vl_logic;
        slb_last_2      : in     vl_logic;
        ram_data_out_14 : in     vl_logic;
        ram_data_out_12 : in     vl_logic;
        ram_data_out_13 : in     vl_logic;
        ram_data_out_15 : in     vl_logic;
        ram_data_out_11 : in     vl_logic;
        ram_data_out_10 : in     vl_logic;
        ram_data_out_9  : in     vl_logic;
        ram_data_out_8  : in     vl_logic;
        ram_data_out_7  : in     vl_logic;
        ram_data_out_6  : in     vl_logic;
        ram_data_out_5  : in     vl_logic;
        ram_data_out_4  : in     vl_logic;
        ram_data_out_3  : in     vl_logic;
        ram_data_out_16 : in     vl_logic;
        ram_data_out_18 : in     vl_logic;
        ram_data_out_17 : in     vl_logic;
        ram_data_out_28 : in     vl_logic;
        ram_data_out_29 : in     vl_logic;
        ram_data_out_30 : in     vl_logic;
        ram_data_out_31 : in     vl_logic;
        ram_data_out_27 : in     vl_logic;
        ram_data_out_26 : in     vl_logic;
        ram_data_out_25 : in     vl_logic;
        ram_data_out_24 : in     vl_logic;
        ram_data_out_23 : in     vl_logic;
        ram_data_out_22 : in     vl_logic;
        ram_data_out_21 : in     vl_logic;
        ram_data_out_20 : in     vl_logic;
        ram_data_out_19 : in     vl_logic;
        clk             : in     vl_logic;
        reset           : in     vl_logic
    );
end fft256_asj_fft_dft_bfp_sgl_fft_121;
