library verilog;
use verilog.vl_types.all;
entity fft256_asj_fft_bfp_i_fft_121 is
    port(
        i_array_out_2_0 : out    vl_logic;
        i_array_out_13_0: out    vl_logic;
        i_array_out_12_0: out    vl_logic;
        i_array_out_11_0: out    vl_logic;
        i_array_out_10_0: out    vl_logic;
        i_array_out_9_0 : out    vl_logic;
        i_array_out_8_0 : out    vl_logic;
        i_array_out_7_0 : out    vl_logic;
        i_array_out_6_0 : out    vl_logic;
        i_array_out_5_0 : out    vl_logic;
        i_array_out_4_0 : out    vl_logic;
        i_array_out_3_0 : out    vl_logic;
        r_array_out_2_0 : out    vl_logic;
        r_array_out_13_0: out    vl_logic;
        r_array_out_12_0: out    vl_logic;
        r_array_out_11_0: out    vl_logic;
        r_array_out_10_0: out    vl_logic;
        r_array_out_9_0 : out    vl_logic;
        r_array_out_8_0 : out    vl_logic;
        r_array_out_7_0 : out    vl_logic;
        r_array_out_6_0 : out    vl_logic;
        r_array_out_5_0 : out    vl_logic;
        r_array_out_4_0 : out    vl_logic;
        r_array_out_3_0 : out    vl_logic;
        global_clock_enable: in     vl_logic;
        i_array_out_1_0 : out    vl_logic;
        i_array_out_0_0 : out    vl_logic;
        i_array_out_15_0: out    vl_logic;
        i_array_out_14_0: out    vl_logic;
        r_array_out_1_0 : out    vl_logic;
        r_array_out_0_0 : out    vl_logic;
        r_array_out_15_0: out    vl_logic;
        r_array_out_14_0: out    vl_logic;
        ram_data_out_0  : in     vl_logic;
        ram_data_out_2  : in     vl_logic;
        slb_last_1      : in     vl_logic;
        ram_data_out_1  : in     vl_logic;
        slb_last_0      : in     vl_logic;
        slb_last_2      : in     vl_logic;
        ram_data_out_14 : in     vl_logic;
        ram_data_out_12 : in     vl_logic;
        ram_data_out_13 : in     vl_logic;
        ram_data_out_15 : in     vl_logic;
        ram_data_out_11 : in     vl_logic;
        ram_data_out_10 : in     vl_logic;
        ram_data_out_9  : in     vl_logic;
        ram_data_out_8  : in     vl_logic;
        ram_data_out_7  : in     vl_logic;
        ram_data_out_6  : in     vl_logic;
        ram_data_out_5  : in     vl_logic;
        ram_data_out_4  : in     vl_logic;
        ram_data_out_3  : in     vl_logic;
        ram_data_out_16 : in     vl_logic;
        ram_data_out_18 : in     vl_logic;
        ram_data_out_17 : in     vl_logic;
        ram_data_out_28 : in     vl_logic;
        ram_data_out_29 : in     vl_logic;
        ram_data_out_30 : in     vl_logic;
        ram_data_out_31 : in     vl_logic;
        ram_data_out_27 : in     vl_logic;
        ram_data_out_26 : in     vl_logic;
        ram_data_out_25 : in     vl_logic;
        ram_data_out_24 : in     vl_logic;
        ram_data_out_23 : in     vl_logic;
        ram_data_out_22 : in     vl_logic;
        ram_data_out_21 : in     vl_logic;
        ram_data_out_20 : in     vl_logic;
        ram_data_out_19 : in     vl_logic;
        clk             : in     vl_logic
    );
end fft256_asj_fft_bfp_i_fft_121;
