library verilog;
use verilog.vl_types.all;
entity fft256_asj_fft_unbburst_sose_ctrl_fft_121 is
    port(
        q_b_0           : in     vl_logic;
        q_b_16          : in     vl_logic;
        q_b_1           : in     vl_logic;
        q_b_17          : in     vl_logic;
        q_b_2           : in     vl_logic;
        q_b_18          : in     vl_logic;
        q_b_3           : in     vl_logic;
        q_b_19          : in     vl_logic;
        q_b_4           : in     vl_logic;
        q_b_20          : in     vl_logic;
        q_b_5           : in     vl_logic;
        q_b_21          : in     vl_logic;
        q_b_6           : in     vl_logic;
        q_b_22          : in     vl_logic;
        q_b_7           : in     vl_logic;
        q_b_23          : in     vl_logic;
        q_b_8           : in     vl_logic;
        q_b_24          : in     vl_logic;
        q_b_9           : in     vl_logic;
        q_b_25          : in     vl_logic;
        q_b_10          : in     vl_logic;
        q_b_26          : in     vl_logic;
        q_b_11          : in     vl_logic;
        q_b_27          : in     vl_logic;
        q_b_12          : in     vl_logic;
        q_b_28          : in     vl_logic;
        q_b_13          : in     vl_logic;
        q_b_29          : in     vl_logic;
        q_b_14          : in     vl_logic;
        q_b_30          : in     vl_logic;
        q_b_15          : in     vl_logic;
        q_b_31          : in     vl_logic;
        pipeline_dffe_16: in     vl_logic;
        pipeline_dffe_17: in     vl_logic;
        pipeline_dffe_18: in     vl_logic;
        pipeline_dffe_19: in     vl_logic;
        pipeline_dffe_20: in     vl_logic;
        pipeline_dffe_21: in     vl_logic;
        pipeline_dffe_22: in     vl_logic;
        pipeline_dffe_23: in     vl_logic;
        pipeline_dffe_24: in     vl_logic;
        pipeline_dffe_25: in     vl_logic;
        pipeline_dffe_26: in     vl_logic;
        pipeline_dffe_27: in     vl_logic;
        pipeline_dffe_28: in     vl_logic;
        pipeline_dffe_29: in     vl_logic;
        pipeline_dffe_30: in     vl_logic;
        pipeline_dffe_31: in     vl_logic;
        global_clock_enable: in     vl_logic;
        a_ram_data_in_bus_0: out    vl_logic;
        wraddress_a_bus_0: out    vl_logic;
        wraddress_a_bus_1: out    vl_logic;
        wraddress_a_bus_2: out    vl_logic;
        wraddress_a_bus_3: out    vl_logic;
        wraddress_a_bus_4: out    vl_logic;
        wraddress_a_bus_5: out    vl_logic;
        wraddress_a_bus_6: out    vl_logic;
        wraddress_a_bus_7: out    vl_logic;
        rdaddress_a_bus_0: out    vl_logic;
        rdaddress_a_bus_1: out    vl_logic;
        rdaddress_a_bus_2: out    vl_logic;
        rdaddress_a_bus_3: out    vl_logic;
        rdaddress_a_bus_4: out    vl_logic;
        rdaddress_a_bus_5: out    vl_logic;
        rdaddress_a_bus_6: out    vl_logic;
        rdaddress_a_bus_7: out    vl_logic;
        a_ram_data_in_bus_16: out    vl_logic;
        a_ram_data_in_bus_1: out    vl_logic;
        a_ram_data_in_bus_17: out    vl_logic;
        a_ram_data_in_bus_2: out    vl_logic;
        a_ram_data_in_bus_18: out    vl_logic;
        a_ram_data_in_bus_3: out    vl_logic;
        a_ram_data_in_bus_19: out    vl_logic;
        a_ram_data_in_bus_4: out    vl_logic;
        a_ram_data_in_bus_20: out    vl_logic;
        a_ram_data_in_bus_5: out    vl_logic;
        a_ram_data_in_bus_21: out    vl_logic;
        a_ram_data_in_bus_6: out    vl_logic;
        a_ram_data_in_bus_22: out    vl_logic;
        a_ram_data_in_bus_7: out    vl_logic;
        a_ram_data_in_bus_23: out    vl_logic;
        a_ram_data_in_bus_8: out    vl_logic;
        a_ram_data_in_bus_24: out    vl_logic;
        a_ram_data_in_bus_9: out    vl_logic;
        a_ram_data_in_bus_25: out    vl_logic;
        a_ram_data_in_bus_10: out    vl_logic;
        a_ram_data_in_bus_26: out    vl_logic;
        a_ram_data_in_bus_11: out    vl_logic;
        a_ram_data_in_bus_27: out    vl_logic;
        a_ram_data_in_bus_12: out    vl_logic;
        a_ram_data_in_bus_28: out    vl_logic;
        a_ram_data_in_bus_13: out    vl_logic;
        a_ram_data_in_bus_29: out    vl_logic;
        a_ram_data_in_bus_14: out    vl_logic;
        a_ram_data_in_bus_30: out    vl_logic;
        a_ram_data_in_bus_15: out    vl_logic;
        a_ram_data_in_bus_31: out    vl_logic;
        data_rdy_vec_21 : in     vl_logic;
        real_out_0      : in     vl_logic;
        data_in_i_0     : in     vl_logic;
        sel_ram_in      : in     vl_logic;
        wraddress_a_bus_ctrl_i_0: in     vl_logic;
        wr_address_i_int_0: in     vl_logic;
        wraddress_a_bus_ctrl_i_1: in     vl_logic;
        wr_address_i_int_1: in     vl_logic;
        wraddress_a_bus_ctrl_i_2: in     vl_logic;
        wr_address_i_int_2: in     vl_logic;
        wraddress_a_bus_ctrl_i_3: in     vl_logic;
        wr_address_i_int_3: in     vl_logic;
        wraddress_a_bus_ctrl_i_4: in     vl_logic;
        wr_address_i_int_4: in     vl_logic;
        wraddress_a_bus_ctrl_i_5: in     vl_logic;
        wr_address_i_int_5: in     vl_logic;
        wraddress_a_bus_ctrl_i_6: in     vl_logic;
        wr_address_i_int_6: in     vl_logic;
        wraddress_a_bus_ctrl_i_7: in     vl_logic;
        wr_address_i_int_7: in     vl_logic;
        rd_addr_a_0     : in     vl_logic;
        rd_addr_a_1     : in     vl_logic;
        rd_addr_a_2     : in     vl_logic;
        rd_addr_a_3     : in     vl_logic;
        rd_addr_a_4     : in     vl_logic;
        rd_addr_a_5     : in     vl_logic;
        rd_addr_a_6     : in     vl_logic;
        rd_addr_a_7     : in     vl_logic;
        data_in_r_0     : in     vl_logic;
        real_out_1      : in     vl_logic;
        data_in_i_1     : in     vl_logic;
        data_in_r_1     : in     vl_logic;
        real_out_2      : in     vl_logic;
        data_in_i_2     : in     vl_logic;
        data_in_r_2     : in     vl_logic;
        real_out_3      : in     vl_logic;
        data_in_i_3     : in     vl_logic;
        data_in_r_3     : in     vl_logic;
        real_out_4      : in     vl_logic;
        data_in_i_4     : in     vl_logic;
        data_in_r_4     : in     vl_logic;
        real_out_5      : in     vl_logic;
        data_in_i_5     : in     vl_logic;
        data_in_r_5     : in     vl_logic;
        real_out_6      : in     vl_logic;
        data_in_i_6     : in     vl_logic;
        data_in_r_6     : in     vl_logic;
        real_out_7      : in     vl_logic;
        data_in_i_7     : in     vl_logic;
        data_in_r_7     : in     vl_logic;
        real_out_8      : in     vl_logic;
        data_in_i_8     : in     vl_logic;
        data_in_r_8     : in     vl_logic;
        real_out_9      : in     vl_logic;
        data_in_i_9     : in     vl_logic;
        data_in_r_9     : in     vl_logic;
        real_out_10     : in     vl_logic;
        data_in_i_10    : in     vl_logic;
        data_in_r_10    : in     vl_logic;
        real_out_11     : in     vl_logic;
        data_in_i_11    : in     vl_logic;
        data_in_r_11    : in     vl_logic;
        real_out_12     : in     vl_logic;
        data_in_i_12    : in     vl_logic;
        data_in_r_12    : in     vl_logic;
        real_out_13     : in     vl_logic;
        data_in_i_13    : in     vl_logic;
        data_in_r_13    : in     vl_logic;
        real_out_14     : in     vl_logic;
        data_in_i_14    : in     vl_logic;
        data_in_r_14    : in     vl_logic;
        real_out_15     : in     vl_logic;
        data_in_i_15    : in     vl_logic;
        data_in_r_15    : in     vl_logic;
        ram_data_out_0  : out    vl_logic;
        ram_data_out_2  : out    vl_logic;
        ram_data_out_1  : out    vl_logic;
        ram_data_out_14 : out    vl_logic;
        ram_data_out_12 : out    vl_logic;
        ram_data_out_13 : out    vl_logic;
        ram_data_out_15 : out    vl_logic;
        ram_data_out_11 : out    vl_logic;
        ram_data_out_10 : out    vl_logic;
        ram_data_out_9  : out    vl_logic;
        ram_data_out_8  : out    vl_logic;
        ram_data_out_7  : out    vl_logic;
        ram_data_out_6  : out    vl_logic;
        ram_data_out_5  : out    vl_logic;
        ram_data_out_4  : out    vl_logic;
        ram_data_out_3  : out    vl_logic;
        ram_data_out_16 : out    vl_logic;
        ram_data_out_18 : out    vl_logic;
        ram_data_out_17 : out    vl_logic;
        ram_data_out_28 : out    vl_logic;
        ram_data_out_29 : out    vl_logic;
        ram_data_out_30 : out    vl_logic;
        ram_data_out_31 : out    vl_logic;
        ram_data_out_27 : out    vl_logic;
        ram_data_out_26 : out    vl_logic;
        ram_data_out_25 : out    vl_logic;
        ram_data_out_24 : out    vl_logic;
        ram_data_out_23 : out    vl_logic;
        ram_data_out_22 : out    vl_logic;
        ram_data_out_21 : out    vl_logic;
        ram_data_out_20 : out    vl_logic;
        ram_data_out_19 : out    vl_logic;
        clk             : in     vl_logic
    );
end fft256_asj_fft_unbburst_sose_ctrl_fft_121;
