library verilog;
use verilog.vl_types.all;
entity fft256_asj_fft_cmult_can_fft_121 is
    port(
        pipeline_dffe_16: out    vl_logic;
        pipeline_dffe_17: out    vl_logic;
        pipeline_dffe_18: out    vl_logic;
        pipeline_dffe_19: out    vl_logic;
        pipeline_dffe_20: out    vl_logic;
        pipeline_dffe_21: out    vl_logic;
        pipeline_dffe_22: out    vl_logic;
        pipeline_dffe_23: out    vl_logic;
        pipeline_dffe_24: out    vl_logic;
        pipeline_dffe_25: out    vl_logic;
        pipeline_dffe_26: out    vl_logic;
        pipeline_dffe_27: out    vl_logic;
        pipeline_dffe_28: out    vl_logic;
        pipeline_dffe_29: out    vl_logic;
        pipeline_dffe_30: out    vl_logic;
        pipeline_dffe_31: out    vl_logic;
        pipeline_dffe_2 : in     vl_logic;
        pipeline_dffe_3 : in     vl_logic;
        pipeline_dffe_4 : in     vl_logic;
        pipeline_dffe_5 : in     vl_logic;
        pipeline_dffe_6 : in     vl_logic;
        pipeline_dffe_7 : in     vl_logic;
        pipeline_dffe_8 : in     vl_logic;
        pipeline_dffe_9 : in     vl_logic;
        pipeline_dffe_10: in     vl_logic;
        pipeline_dffe_11: in     vl_logic;
        pipeline_dffe_12: in     vl_logic;
        pipeline_dffe_13: in     vl_logic;
        pipeline_dffe_14: in     vl_logic;
        pipeline_dffe_15: in     vl_logic;
        pipeline_dffe_161: in     vl_logic;
        pipeline_dffe_171: in     vl_logic;
        twiddle_data_real_0: in     vl_logic;
        twiddle_data_real_15: in     vl_logic;
        pipeline_dffe_210: in     vl_logic;
        pipeline_dffe_32: in     vl_logic;
        pipeline_dffe_41: in     vl_logic;
        pipeline_dffe_51: in     vl_logic;
        pipeline_dffe_61: in     vl_logic;
        pipeline_dffe_71: in     vl_logic;
        pipeline_dffe_81: in     vl_logic;
        pipeline_dffe_91: in     vl_logic;
        pipeline_dffe_101: in     vl_logic;
        pipeline_dffe_111: in     vl_logic;
        pipeline_dffe_121: in     vl_logic;
        pipeline_dffe_131: in     vl_logic;
        pipeline_dffe_141: in     vl_logic;
        pipeline_dffe_151: in     vl_logic;
        pipeline_dffe_162: in     vl_logic;
        pipeline_dffe_172: in     vl_logic;
        twiddle_data_imag_1: in     vl_logic;
        twiddle_data_imag_2: in     vl_logic;
        twiddle_data_imag_3: in     vl_logic;
        twiddle_data_imag_4: in     vl_logic;
        twiddle_data_imag_5: in     vl_logic;
        twiddle_data_imag_6: in     vl_logic;
        twiddle_data_imag_7: in     vl_logic;
        twiddle_data_imag_8: in     vl_logic;
        twiddle_data_imag_9: in     vl_logic;
        twiddle_data_imag_10: in     vl_logic;
        twiddle_data_imag_11: in     vl_logic;
        twiddle_data_imag_12: in     vl_logic;
        twiddle_data_imag_13: in     vl_logic;
        twiddle_data_imag_14: in     vl_logic;
        twiddle_data_imag_15: in     vl_logic;
        global_clock_enable: in     vl_logic;
        real_out_0      : out    vl_logic;
        real_out_1      : out    vl_logic;
        real_out_2      : out    vl_logic;
        real_out_3      : out    vl_logic;
        real_out_4      : out    vl_logic;
        real_out_5      : out    vl_logic;
        real_out_6      : out    vl_logic;
        real_out_7      : out    vl_logic;
        real_out_8      : out    vl_logic;
        real_out_9      : out    vl_logic;
        real_out_10     : out    vl_logic;
        real_out_11     : out    vl_logic;
        real_out_12     : out    vl_logic;
        real_out_13     : out    vl_logic;
        real_out_14     : out    vl_logic;
        real_out_15     : out    vl_logic;
        twiddle_data_real_1: in     vl_logic;
        twiddle_data_real_2: in     vl_logic;
        twiddle_data_real_3: in     vl_logic;
        twiddle_data_real_4: in     vl_logic;
        twiddle_data_real_5: in     vl_logic;
        twiddle_data_real_6: in     vl_logic;
        twiddle_data_real_7: in     vl_logic;
        twiddle_data_real_8: in     vl_logic;
        twiddle_data_real_9: in     vl_logic;
        twiddle_data_real_10: in     vl_logic;
        twiddle_data_real_11: in     vl_logic;
        twiddle_data_real_12: in     vl_logic;
        twiddle_data_real_13: in     vl_logic;
        twiddle_data_real_14: in     vl_logic;
        twiddle_data_imag_0: in     vl_logic;
        clk             : in     vl_logic;
        reset           : in     vl_logic
    );
end fft256_asj_fft_cmult_can_fft_121;
