library verilog;
use verilog.vl_types.all;
entity fft256_asj_fft_si_sose_so_b_fft_121 is
    port(
        at_sink_ready_s : out    vl_logic;
        at_source_error_0: out    vl_logic;
        at_source_error_1: out    vl_logic;
        at_source_sop_s : out    vl_logic;
        at_source_eop_s : out    vl_logic;
        at_source_valid_s: out    vl_logic;
        at_source_data_0: out    vl_logic;
        at_source_data_1: out    vl_logic;
        at_source_data_2: out    vl_logic;
        at_source_data_3: out    vl_logic;
        at_source_data_4: out    vl_logic;
        at_source_data_5: out    vl_logic;
        at_source_data_22: out    vl_logic;
        at_source_data_23: out    vl_logic;
        at_source_data_24: out    vl_logic;
        at_source_data_25: out    vl_logic;
        at_source_data_26: out    vl_logic;
        at_source_data_27: out    vl_logic;
        at_source_data_28: out    vl_logic;
        at_source_data_29: out    vl_logic;
        at_source_data_30: out    vl_logic;
        at_source_data_31: out    vl_logic;
        at_source_data_32: out    vl_logic;
        at_source_data_33: out    vl_logic;
        at_source_data_34: out    vl_logic;
        at_source_data_35: out    vl_logic;
        at_source_data_36: out    vl_logic;
        at_source_data_37: out    vl_logic;
        at_source_data_6: out    vl_logic;
        at_source_data_7: out    vl_logic;
        at_source_data_8: out    vl_logic;
        at_source_data_9: out    vl_logic;
        at_source_data_10: out    vl_logic;
        at_source_data_11: out    vl_logic;
        at_source_data_12: out    vl_logic;
        at_source_data_13: out    vl_logic;
        at_source_data_14: out    vl_logic;
        at_source_data_15: out    vl_logic;
        at_source_data_16: out    vl_logic;
        at_source_data_17: out    vl_logic;
        at_source_data_18: out    vl_logic;
        at_source_data_19: out    vl_logic;
        at_source_data_20: out    vl_logic;
        at_source_data_21: out    vl_logic;
        GND_port        : in     vl_logic;
        clk             : in     vl_logic;
        reset_n         : in     vl_logic;
        source_ready    : in     vl_logic;
        sink_valid      : in     vl_logic;
        sink_sop        : in     vl_logic;
        sink_eop        : in     vl_logic;
        sink_error_0    : in     vl_logic;
        sink_error_1    : in     vl_logic;
        inverse         : in     vl_logic;
        sink_real       : in     vl_logic_vector(15 downto 0);
        sink_imag       : in     vl_logic_vector(15 downto 0)
    );
end fft256_asj_fft_si_sose_so_b_fft_121;
