library verilog;
use verilog.vl_types.all;
entity fft256_asj_fft_1dp_ram_fft_121 is
    port(
        q_b_0           : out    vl_logic;
        q_b_16          : out    vl_logic;
        q_b_1           : out    vl_logic;
        q_b_17          : out    vl_logic;
        q_b_2           : out    vl_logic;
        q_b_18          : out    vl_logic;
        q_b_3           : out    vl_logic;
        q_b_19          : out    vl_logic;
        q_b_4           : out    vl_logic;
        q_b_20          : out    vl_logic;
        q_b_5           : out    vl_logic;
        q_b_21          : out    vl_logic;
        q_b_6           : out    vl_logic;
        q_b_22          : out    vl_logic;
        q_b_7           : out    vl_logic;
        q_b_23          : out    vl_logic;
        q_b_8           : out    vl_logic;
        q_b_24          : out    vl_logic;
        q_b_9           : out    vl_logic;
        q_b_25          : out    vl_logic;
        q_b_10          : out    vl_logic;
        q_b_26          : out    vl_logic;
        q_b_11          : out    vl_logic;
        q_b_27          : out    vl_logic;
        q_b_12          : out    vl_logic;
        q_b_28          : out    vl_logic;
        q_b_13          : out    vl_logic;
        q_b_29          : out    vl_logic;
        q_b_14          : out    vl_logic;
        q_b_30          : out    vl_logic;
        q_b_15          : out    vl_logic;
        q_b_31          : out    vl_logic;
        global_clock_enable: in     vl_logic;
        wren_a          : in     vl_logic;
        a_ram_data_in_bus_0: in     vl_logic;
        wraddress_a_bus_0: in     vl_logic;
        wraddress_a_bus_1: in     vl_logic;
        wraddress_a_bus_2: in     vl_logic;
        wraddress_a_bus_3: in     vl_logic;
        wraddress_a_bus_4: in     vl_logic;
        wraddress_a_bus_5: in     vl_logic;
        wraddress_a_bus_6: in     vl_logic;
        wraddress_a_bus_7: in     vl_logic;
        rdaddress_a_bus_0: in     vl_logic;
        rdaddress_a_bus_1: in     vl_logic;
        rdaddress_a_bus_2: in     vl_logic;
        rdaddress_a_bus_3: in     vl_logic;
        rdaddress_a_bus_4: in     vl_logic;
        rdaddress_a_bus_5: in     vl_logic;
        rdaddress_a_bus_6: in     vl_logic;
        rdaddress_a_bus_7: in     vl_logic;
        a_ram_data_in_bus_16: in     vl_logic;
        a_ram_data_in_bus_1: in     vl_logic;
        a_ram_data_in_bus_17: in     vl_logic;
        a_ram_data_in_bus_2: in     vl_logic;
        a_ram_data_in_bus_18: in     vl_logic;
        a_ram_data_in_bus_3: in     vl_logic;
        a_ram_data_in_bus_19: in     vl_logic;
        a_ram_data_in_bus_4: in     vl_logic;
        a_ram_data_in_bus_20: in     vl_logic;
        a_ram_data_in_bus_5: in     vl_logic;
        a_ram_data_in_bus_21: in     vl_logic;
        a_ram_data_in_bus_6: in     vl_logic;
        a_ram_data_in_bus_22: in     vl_logic;
        a_ram_data_in_bus_7: in     vl_logic;
        a_ram_data_in_bus_23: in     vl_logic;
        a_ram_data_in_bus_8: in     vl_logic;
        a_ram_data_in_bus_24: in     vl_logic;
        a_ram_data_in_bus_9: in     vl_logic;
        a_ram_data_in_bus_25: in     vl_logic;
        a_ram_data_in_bus_10: in     vl_logic;
        a_ram_data_in_bus_26: in     vl_logic;
        a_ram_data_in_bus_11: in     vl_logic;
        a_ram_data_in_bus_27: in     vl_logic;
        a_ram_data_in_bus_12: in     vl_logic;
        a_ram_data_in_bus_28: in     vl_logic;
        a_ram_data_in_bus_13: in     vl_logic;
        a_ram_data_in_bus_29: in     vl_logic;
        a_ram_data_in_bus_14: in     vl_logic;
        a_ram_data_in_bus_30: in     vl_logic;
        a_ram_data_in_bus_15: in     vl_logic;
        a_ram_data_in_bus_31: in     vl_logic;
        clk             : in     vl_logic
    );
end fft256_asj_fft_1dp_ram_fft_121;
