library verilog;
use verilog.vl_types.all;
entity fft256_auk_dspip_avalon_streaming_source_fft_121 is
    port(
        data_count      : in     vl_logic_vector(7 downto 0);
        at_source_error_0: out    vl_logic;
        at_source_error_1: out    vl_logic;
        at_source_sop_s1: out    vl_logic;
        at_source_eop_s1: out    vl_logic;
        at_source_valid_s1: out    vl_logic;
        at_source_data_0: out    vl_logic;
        at_source_data_1: out    vl_logic;
        at_source_data_2: out    vl_logic;
        at_source_data_3: out    vl_logic;
        at_source_data_4: out    vl_logic;
        at_source_data_5: out    vl_logic;
        at_source_data_22: out    vl_logic;
        at_source_data_23: out    vl_logic;
        at_source_data_24: out    vl_logic;
        at_source_data_25: out    vl_logic;
        at_source_data_26: out    vl_logic;
        at_source_data_27: out    vl_logic;
        at_source_data_28: out    vl_logic;
        at_source_data_29: out    vl_logic;
        at_source_data_30: out    vl_logic;
        at_source_data_31: out    vl_logic;
        at_source_data_32: out    vl_logic;
        at_source_data_33: out    vl_logic;
        at_source_data_34: out    vl_logic;
        at_source_data_35: out    vl_logic;
        at_source_data_36: out    vl_logic;
        at_source_data_37: out    vl_logic;
        at_source_data_6: out    vl_logic;
        at_source_data_7: out    vl_logic;
        at_source_data_8: out    vl_logic;
        at_source_data_9: out    vl_logic;
        at_source_data_10: out    vl_logic;
        at_source_data_11: out    vl_logic;
        at_source_data_12: out    vl_logic;
        at_source_data_13: out    vl_logic;
        at_source_data_14: out    vl_logic;
        at_source_data_15: out    vl_logic;
        at_source_data_16: out    vl_logic;
        at_source_data_17: out    vl_logic;
        at_source_data_18: out    vl_logic;
        at_source_data_19: out    vl_logic;
        at_source_data_20: out    vl_logic;
        at_source_data_21: out    vl_logic;
        source_packet_error_0: in     vl_logic;
        source_packet_error_1: in     vl_logic;
        source_stall_reg: in     vl_logic;
        master_source_ena: in     vl_logic;
        source_valid_ctrl_sop: in     vl_logic;
        source_valid_ctrl_sop1: in     vl_logic;
        stall_reg       : in     vl_logic;
        source_stall_int_d1: out    vl_logic;
        data            : in     vl_logic_vector(37 downto 0);
        Mux0            : out    vl_logic;
        clk             : in     vl_logic;
        reset_n         : in     vl_logic;
        source_ready    : in     vl_logic
    );
end fft256_auk_dspip_avalon_streaming_source_fft_121;
