set_property PACKAGE_PIN R4 [get_ports sys_clk]
set_property PACKAGE_PIN T3 [get_ports rst_n]
set_property PACKAGE_PIN D19 [get_ports clk_adc]
set_property PACKAGE_PIN B22 [get_ports clk_dac]
set_property PACKAGE_PIN C20 [get_ports clk_fir]
set_property PACKAGE_PIN D22 [get_ports ligth]
set_property PACKAGE_PIN F20 [get_ports locked]
set_property PACKAGE_PIN H15 [get_ports {dac_out[12]}]
set_property PACKAGE_PIN G16 [get_ports {dac_out[10]}]
set_property PACKAGE_PIN G18 [get_ports {dac_out[8]}]
set_property PACKAGE_PIN H18 [get_ports {dac_out[6]}]
set_property PACKAGE_PIN H19 [get_ports {dac_out[4]}]
set_property PACKAGE_PIN G20 [get_ports {dac_out[2]}]
set_property PACKAGE_PIN J21 [get_ports {dac_out[0]}]
set_property PACKAGE_PIN J15 [get_ports {dac_out[13]}]
set_property PACKAGE_PIN G15 [get_ports {dac_out[11]}]
set_property PACKAGE_PIN G17 [get_ports {dac_out[9]}]
set_property PACKAGE_PIN H17 [get_ports {dac_out[7]}]
set_property PACKAGE_PIN J19 [get_ports {dac_out[5]}]
set_property PACKAGE_PIN H20 [get_ports {dac_out[3]}]
set_property PACKAGE_PIN J20 [get_ports {dac_out[1]}]

set_property IOSTANDARD LVCMOS33 [get_ports clk_adc]
set_property IOSTANDARD LVCMOS33 [get_ports clk_fir]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports ligth]
set_property IOSTANDARD LVCMOS33 [get_ports locked]
set_property IOSTANDARD LVCMOS33 [get_ports clk_dac]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_out[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_out[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_out[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_out[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_out[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_out[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_out[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_out[1]}]

# set_false_path -from [get_ports valid]
set_false_path -from [get_ports rst_n]
# create_clock -period 20.000 -name sys_clk -waveform {0.000 10.000} -add [get_ports *sys_clk*]
# set_input_jitter [get_clocks *sys_clk*] 0.200
