library verilog;
use verilog.vl_types.all;
entity fft256_LPM_ADD_SUB_1 is
    port(
        pipeline_dffe_16: out    vl_logic;
        pipeline_dffe_17: out    vl_logic;
        pipeline_dffe_18: out    vl_logic;
        pipeline_dffe_19: out    vl_logic;
        pipeline_dffe_20: out    vl_logic;
        pipeline_dffe_21: out    vl_logic;
        pipeline_dffe_22: out    vl_logic;
        pipeline_dffe_23: out    vl_logic;
        pipeline_dffe_24: out    vl_logic;
        pipeline_dffe_25: out    vl_logic;
        pipeline_dffe_26: out    vl_logic;
        pipeline_dffe_27: out    vl_logic;
        pipeline_dffe_28: out    vl_logic;
        pipeline_dffe_29: out    vl_logic;
        pipeline_dffe_30: out    vl_logic;
        pipeline_dffe_31: out    vl_logic;
        result_real_1_tmp_16: in     vl_logic;
        result_real_1_tmp_15: in     vl_logic;
        result_real_1_tmp_14: in     vl_logic;
        result_real_1_tmp_13: in     vl_logic;
        result_real_1_tmp_12: in     vl_logic;
        result_real_1_tmp_11: in     vl_logic;
        result_real_1_tmp_10: in     vl_logic;
        result_real_1_tmp_9: in     vl_logic;
        result_real_1_tmp_8: in     vl_logic;
        result_real_1_tmp_7: in     vl_logic;
        result_real_1_tmp_6: in     vl_logic;
        result_real_1_tmp_5: in     vl_logic;
        result_real_1_tmp_4: in     vl_logic;
        result_real_1_tmp_3: in     vl_logic;
        result_real_1_tmp_2: in     vl_logic;
        result_real_1_tmp_1: in     vl_logic;
        result_real_1_tmp_0: in     vl_logic;
        result_real_1_tmp_31: in     vl_logic;
        result_real_1_tmp_17: in     vl_logic;
        result_real_1_tmp_18: in     vl_logic;
        result_real_1_tmp_19: in     vl_logic;
        result_real_1_tmp_20: in     vl_logic;
        result_real_1_tmp_21: in     vl_logic;
        result_real_1_tmp_22: in     vl_logic;
        result_real_1_tmp_23: in     vl_logic;
        result_real_1_tmp_24: in     vl_logic;
        result_real_1_tmp_25: in     vl_logic;
        result_real_1_tmp_26: in     vl_logic;
        result_real_1_tmp_27: in     vl_logic;
        result_real_1_tmp_28: in     vl_logic;
        result_real_1_tmp_29: in     vl_logic;
        result_real_1_tmp_30: in     vl_logic;
        clken           : in     vl_logic;
        clock           : in     vl_logic
    );
end fft256_LPM_ADD_SUB_1;
