library verilog;
use verilog.vl_types.all;
entity fft256_asj_fft_in_write_sgl_fft_121 is
    port(
        disable_wr1     : out    vl_logic;
        rdy_for_next_block1: out    vl_logic;
        core_imag_in_0  : in     vl_logic;
        core_real_in_0  : in     vl_logic;
        core_imag_in_1  : in     vl_logic;
        core_real_in_1  : in     vl_logic;
        core_imag_in_2  : in     vl_logic;
        core_real_in_2  : in     vl_logic;
        core_imag_in_3  : in     vl_logic;
        core_real_in_3  : in     vl_logic;
        core_imag_in_4  : in     vl_logic;
        core_real_in_4  : in     vl_logic;
        core_imag_in_5  : in     vl_logic;
        core_real_in_5  : in     vl_logic;
        core_imag_in_6  : in     vl_logic;
        core_real_in_6  : in     vl_logic;
        core_imag_in_7  : in     vl_logic;
        core_real_in_7  : in     vl_logic;
        core_imag_in_8  : in     vl_logic;
        core_real_in_8  : in     vl_logic;
        core_imag_in_9  : in     vl_logic;
        core_real_in_9  : in     vl_logic;
        core_imag_in_10 : in     vl_logic;
        core_real_in_10 : in     vl_logic;
        core_imag_in_11 : in     vl_logic;
        core_real_in_11 : in     vl_logic;
        core_imag_in_12 : in     vl_logic;
        core_real_in_12 : in     vl_logic;
        core_imag_in_13 : in     vl_logic;
        core_real_in_13 : in     vl_logic;
        core_imag_in_14 : in     vl_logic;
        core_real_in_14 : in     vl_logic;
        core_imag_in_15 : in     vl_logic;
        core_real_in_15 : in     vl_logic;
        data_rdy_int1   : out    vl_logic;
        send_sop_s      : in     vl_logic;
        global_clock_enable: in     vl_logic;
        blk_done        : in     vl_logic;
        tdl_arr_0       : out    vl_logic;
        data_in_i_0     : out    vl_logic;
        wr_address_i_int_0: out    vl_logic;
        wr_address_i_int_1: out    vl_logic;
        wr_address_i_int_2: out    vl_logic;
        wr_address_i_int_3: out    vl_logic;
        wr_address_i_int_4: out    vl_logic;
        wr_address_i_int_5: out    vl_logic;
        wr_address_i_int_6: out    vl_logic;
        wr_address_i_int_7: out    vl_logic;
        data_in_r_0     : out    vl_logic;
        data_in_i_1     : out    vl_logic;
        data_in_r_1     : out    vl_logic;
        data_in_i_2     : out    vl_logic;
        data_in_r_2     : out    vl_logic;
        data_in_i_3     : out    vl_logic;
        data_in_r_3     : out    vl_logic;
        data_in_i_4     : out    vl_logic;
        data_in_r_4     : out    vl_logic;
        data_in_i_5     : out    vl_logic;
        data_in_r_5     : out    vl_logic;
        data_in_i_6     : out    vl_logic;
        data_in_r_6     : out    vl_logic;
        data_in_i_7     : out    vl_logic;
        data_in_r_7     : out    vl_logic;
        data_in_i_8     : out    vl_logic;
        data_in_r_8     : out    vl_logic;
        data_in_i_9     : out    vl_logic;
        data_in_r_9     : out    vl_logic;
        data_in_i_10    : out    vl_logic;
        data_in_r_10    : out    vl_logic;
        data_in_i_11    : out    vl_logic;
        data_in_r_11    : out    vl_logic;
        data_in_i_12    : out    vl_logic;
        data_in_r_12    : out    vl_logic;
        data_in_i_13    : out    vl_logic;
        data_in_r_13    : out    vl_logic;
        data_in_i_14    : out    vl_logic;
        data_in_r_14    : out    vl_logic;
        data_in_i_15    : out    vl_logic;
        data_in_r_15    : out    vl_logic;
        counter_i       : out    vl_logic;
        clk             : in     vl_logic;
        reset_n         : in     vl_logic
    );
end fft256_asj_fft_in_write_sgl_fft_121;
