set_property PACKAGE_PIN R4 [get_ports sys_clk]
set_property PACKAGE_PIN T3 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]
# DAC连线和电平标准
set_property PACKAGE_PIN H14 [get_ports clk_dac]
set_property IOSTANDARD LVCMOS33 [get_ports clk_dac]

set_property PACKAGE_PIN H15 [get_ports {dac_data[12]}]
set_property PACKAGE_PIN G16 [get_ports {dac_data[10]}]
set_property PACKAGE_PIN G18 [get_ports {dac_data[8]}]
set_property PACKAGE_PIN H18 [get_ports {dac_data[6]}]
set_property PACKAGE_PIN H19 [get_ports {dac_data[4]}]
set_property PACKAGE_PIN G20 [get_ports {dac_data[2]}]
set_property PACKAGE_PIN J21 [get_ports {dac_data[0]}]

set_property PACKAGE_PIN J15 [get_ports {dac_data[13]}]
set_property PACKAGE_PIN G15 [get_ports {dac_data[11]}]
set_property PACKAGE_PIN G17 [get_ports {dac_data[9]}]
set_property PACKAGE_PIN H17 [get_ports {dac_data[7]}]
set_property PACKAGE_PIN J19 [get_ports {dac_data[5]}]
set_property PACKAGE_PIN H20 [get_ports {dac_data[3]}]
set_property PACKAGE_PIN J20 [get_ports {dac_data[1]}]

set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[1]}]

# ADC连线和电平标准
set_property PACKAGE_PIN G13 [get_ports clk_adc]
set_property IOSTANDARD LVCMOS33 [get_ports clk_adc]

set_property PACKAGE_PIN G22 [get_ports {adc_data[10]}]
set_property PACKAGE_PIN D21 [get_ports {adc_data[8]}]
set_property PACKAGE_PIN D22 [get_ports {adc_data[6]}]
set_property PACKAGE_PIN F20 [get_ports {adc_data[4]}]
set_property PACKAGE_PIN C20 [get_ports {adc_data[2]}]
set_property PACKAGE_PIN B22 [get_ports {adc_data[0]}]

set_property PACKAGE_PIN H13 [get_ports {adc_data[11]}]
set_property PACKAGE_PIN G21 [get_ports {adc_data[9]}]
set_property PACKAGE_PIN E21 [get_ports {adc_data[7]}]
set_property PACKAGE_PIN E22 [get_ports {adc_data[5]}]
set_property PACKAGE_PIN F19 [get_ports {adc_data[3]}]
set_property PACKAGE_PIN D20 [get_ports {adc_data[1]}]
set_property PACKAGE_PIN C22 [get_ports OTR]

set_property IOSTANDARD LVCMOS33 [get_ports {adc_data[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {adc_data[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports OTR]

set_false_path -from [get_ports rst_n]

set_false_path -from [get_ports {adc_data[10]}]
set_false_path -from [get_ports {adc_data[8]}]
set_false_path -from [get_ports {adc_data[6]}]
set_false_path -from [get_ports {adc_data[4]}]
set_false_path -from [get_ports {adc_data[2]}]
set_false_path -from [get_ports {adc_data[0]}]
set_false_path -from [get_ports {adc_data[11]}]
set_false_path -from [get_ports {adc_data[9]}]
set_false_path -from [get_ports {adc_data[7]}]
set_false_path -from [get_ports {adc_data[5]}]
set_false_path -from [get_ports {adc_data[3]}]
set_false_path -from [get_ports {adc_data[1]}]
set_false_path -from [get_ports OTR]

# create_clock -period 20.000 -name sys_clk -waveform {0.000 10.000} -add [get_ports *sys_clk*]
# set_input_jitter [get_clocks *sys_clk*] 0.200