library verilog;
use verilog.vl_types.all;
entity fft256_asj_fft_1tdp_rom_fft_121 is
    port(
        q_a_0           : out    vl_logic;
        q_b_0           : out    vl_logic;
        q_a_1           : out    vl_logic;
        q_b_1           : out    vl_logic;
        q_a_2           : out    vl_logic;
        q_b_2           : out    vl_logic;
        q_a_3           : out    vl_logic;
        q_b_3           : out    vl_logic;
        q_a_4           : out    vl_logic;
        q_b_4           : out    vl_logic;
        q_a_5           : out    vl_logic;
        q_b_5           : out    vl_logic;
        q_a_6           : out    vl_logic;
        q_b_6           : out    vl_logic;
        q_a_7           : out    vl_logic;
        q_b_7           : out    vl_logic;
        q_a_8           : out    vl_logic;
        q_b_8           : out    vl_logic;
        q_a_9           : out    vl_logic;
        q_b_9           : out    vl_logic;
        q_a_10          : out    vl_logic;
        q_b_10          : out    vl_logic;
        q_a_11          : out    vl_logic;
        q_b_11          : out    vl_logic;
        q_a_12          : out    vl_logic;
        q_b_12          : out    vl_logic;
        q_a_13          : out    vl_logic;
        q_b_13          : out    vl_logic;
        q_a_14          : out    vl_logic;
        q_b_14          : out    vl_logic;
        q_a_15          : out    vl_logic;
        q_b_15          : out    vl_logic;
        twad_tempo_0    : in     vl_logic;
        twad_tempe_1    : in     vl_logic;
        twad_tempe_2    : in     vl_logic;
        twad_tempe_3    : in     vl_logic;
        twad_tempe_4    : in     vl_logic;
        twad_tempe_5    : in     vl_logic;
        twad_tempo_1    : in     vl_logic;
        twad_tempo_2    : in     vl_logic;
        twad_tempo_3    : in     vl_logic;
        twad_tempo_4    : in     vl_logic;
        twad_tempo_5    : in     vl_logic;
        global_clock_enable: in     vl_logic;
        GND_port        : in     vl_logic;
        clk             : in     vl_logic
    );
end fft256_asj_fft_1tdp_rom_fft_121;
